### ISSUE TITLE
[Requirements] Audience for this resources vs the statements themselves

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-statements#14]
[Audiences section](https://www.w3.org/WAI/EO/wiki/Accessibility_Statements_Requirements#Audience) mixes different audiences:
1. Audiences for ***this resources*** that helps people create accessibility statements.
2. Audiences of the accessibility statements themselves. (e.g., "Users with disabilities" and "Other users of accessibility statements")

To limit confusion, I think keep the main Audience section **just for this document**.

In a later section of this Requirements doc, you can list who are the audiences for the accessibility statements themselves. -- which might actually end up in the detailed version of the resource :-)

**Comment by AccessibilityNL** [comment]
Hi Shawn. Sorry I did not see this comment before. Is it still relevant? If yes, could you explain a bit more what you mean by the comment or clarify where a change is needed?

**Comment by slhenry** [comment]
[Accessibility Statements Requirements, Audience section](https://www.w3.org/WAI/EO/wiki/Accessibility_Statements_Requirements#Audience) should include *only* the audiences *of the resource that we're developing* -- not the audiences of the resulting accessibility statements.

This is the direct audience of the resource that we are developing:
* Persons who need to create an accessibility statement: 

These are ***not*** audiences of the resource that we're developing – that is, they mostly won't read our document. So they shouldn't be in this section. (They could be later in this Requirements doc, or not in it at all -- just in the resource itself.)
* Users with disabilities: 
* Other users of accessibility statements:
* Researchers and other interested persons/organizations:

It's not clear enough which these are:
* Accessibility Champions:
* Corporate Social Responsibility officers:

**Comment by nitedog** [comment]
I agree that these audiences can be removed from the "audience section", because they are not the target audience of this resource. "Accessibility champions/advocates" and "CSR officers" could be kept there as secondary audience of this resource. However, it is important to clarify the end users of the resulting reports that are generated by this guidance, namely people (users) with disabilities. This will be relevant when reviewing some of the examples and content generated by the tool we want to develop.
