### ISSUE TITLE
[ED] add information on following through with comments received

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-statements#78]
From @dboudreau 

> One thing that might be missing in the document is a section on following
through with comments received by end users. It's one thing to have contact
information to get in touch with the organization about problems we may
encounter on the site, but it's another entirely to have a process in place
for the organization to actually RECEIVE, and ACT UPON that feedback. Most
lawsuits out there are the result of escalations after someone tried to
reach out, and was either dismissed, not acknowledged, or shown very little
empathy. I'm wondering if it would be worthwhile to include something along
those lines as part of the document, maybe as a form of cautionary tale or
something.

**Comment by bakkenb** [comment]
I completely understand what you are saying @dboudreau. This would be very helpful advice for organizations. I believe, however, that this is just a bit past the scope of the purpose and objectives of this resource. There should be some assumptions made on the part of the organization that if they are providing an estimated timeline for follow-up, that they would think through that process and workflow for actually meeting that timeline that they are publishing. 

I know that that is wishful thinking, and it probably does not happen internally for various reasons. I just wonder how far down the road we should go to advising organizations about internal processes particularly in this resource. I can be convinced that a simple statement could be added, because many of our other resources do provide much advice into developing internal processes to follow-up with accessibility commitments. Maybe Shadi is right to think of linking to an existing resource. 

I am keeping my mind open to what others think about this. Welcome more input.
I do not believe this should hold up publication (and I am guessing you are too Denis). 
Fine with Editors discretion.

**Comment by dboudreau** [comment]
Good points. I sense scope creep. A'ight, I'm backing off. :)

**Comment by nitedog** [comment]
Thanks @dboudreau - I see now easy way of adding this without quite some scope creeping.
