### ISSUE TITLE
[ED] Write out month in date

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-statements#82]
e.g. 01/02/2018
&nbsp;&nbsp;->&nbsp;1 February 2018

**Comment by slhenry** [comment]
/me was surprised to find when she cleared the date that it says mm/dd/yyyy instead of dd/ww/yyyy

**Comment by rvantonisse** [comment]
**Solution options**: 
- leave as is
- Apply a format on the date output in the generated statement
- change date input to text input so a user can decide what the date output will be

**Explanation**
Date input type is a bit of a pain to get a behaviour that is the same in every browser. Currently if a browser does support the date typed input, the browser implements its own kind of date picker which provides a nice user interface to pick a date. If not it defaults to a text input without this nice user interface.

> e.g. 01/02/2018 -> 1 February 2018

What the format is for a date input is system / browser specific. Enabling a different date input format is possible, but would require a lot of code effort. Instead it is easier to apply this readable date format as output in the generated statement by either change the input type to text or apply a pretty format on the date output.

> /me was surprised to find when she cleared the date that it says mm/dd/yyyy instead of dd/mm/yyyy

I think this is because of local / date settings on your system / browser used.

**Comment by slhenry** [comment]
Rationale: A lot of people don't even realize that 01/02/yyyy is different dates in different parts of the world.

If the date was very important, then I would strongly support doing more to make the outputted date clear -- that is, write out the month.

However, I think the date is not super important for most accessibility statements. Therefore, I'd be OK leaving it if others thinks that is best.

> Apply a format on the date output in the generated statement

I mildly prefer this option.

**Comment by yatil** [comment]
[My comment is not blocking publication.]

I wonder if we should not just have a text field and output it as verbatim. That way, people can also write December 2018 if they want without a date.

**Comment by rvantonisse** [comment]
(Option 3) Changing date input into text is most easy option to apply and gives full control on in and output to the user. Only (minor) disadvantage is losing date picking functionality for supporting browsers.

I prefer this for reasons that the user will have full control over input and output.

Option 2 is still forcing a user into a date format and requires me to add some code.

I will implement option 3

**Comment by nitedog** [comment]
Change made as described above.
